// [Render System]
const GAME_WINDOW_WIDTH = 1280
const GAME_WINDOW_HEIGHT = 720

// [Physics System]
const FRICTION_COEFFICIENT = 0.95

// [Field Effect System]
const MIN_EFFECT_TIME = 5000
const MAX_EFFECT_TIME = 10000
const MIN_EFFECT_INTERVAL_TIME = 1000
const MAX_EFFECT_INTERVAL_TIME = 2000

// [Game Objects]
// These velocities are in pixels/seconds
const PADDLE_ACCELERATION = 1000
const MAX_PADDLE_VELOCITY = 400
const LOW_FRICTION_MAX_PADDLE_VELOCITY = 500

const INITIAL_BALL_VEL_MAG = 375
const BALL_VEL_INCREASE_RATE = 0.05
const POWER_PADDLE_BALL_VEL_MAG = 1000

export {
    GAME_WINDOW_WIDTH,
    GAME_WINDOW_HEIGHT,
    
    FRICTION_COEFFICIENT,
    
    MIN_EFFECT_INTERVAL_TIME,
    MAX_EFFECT_INTERVAL_TIME,
    MIN_EFFECT_TIME,
    MAX_EFFECT_TIME,

    PADDLE_ACCELERATION,
    MAX_PADDLE_VELOCITY,
    LOW_FRICTION_MAX_PADDLE_VELOCITY,
    
    INITIAL_BALL_VEL_MAG,
    BALL_VEL_INCREASE_RATE,
    POWER_PADDLE_BALL_VEL_MAG,
}
